package com.myproject.forms;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;

import org.jfree.data.category.DefaultCategoryDataset;

import org.jfree.data.general.DefaultPieDataset;


public class Form_Statement extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_Statement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tabbedPane = new JTabbedPane();
        tabbedPane.setBackground(new java.awt.Color(28, 181, 224));
        tabbedPane.setForeground(java.awt.Color.WHITE);
        
        panel1 = new JPanel();
        setDataToColumnChart(panel1, "Tháng");
        tabbedPane.addTab("Tổng doanh thu trong từng tháng", panel1);

        panel2 = new JPanel();
        setDataToPieChart(panel2);
        tabbedPane.addTab("Thành phần doanh thu trong tháng theo loại phòng", panel2);
        
        panel3 = new JPanel();
        setDataToPieChart(panel3);
        tabbedPane.addTab("Thành phần doanh thu trong tháng theo loại dịch vụ ", panel3);

        label1 = new JLabel();
        label1.setText("Chọn thời gian bắt đầu:");
        label2 = new JLabel();
        label2.setText("Chọn thời gian kết thúc:");
        
        cbBox1 = new JComboBox();
        cbBox3 = new JComboBox();
        for (int i = 1; i < 13; i++){
            String temp = "Tháng " + i;
            cbBox1.addItem(temp);
            cbBox3.addItem(temp);
        }
        cbBox1.setSelectedIndex(0);
        cbBox3.setSelectedIndex(0);
        
        cbBox2 = new JComboBox();
        cbBox4 = new JComboBox();
        for (int i = 2018; i < 2024; i++){
            String temp = "Năm " + i;
            cbBox2.addItem(temp);
            cbBox4.addItem(temp);
        }
        cbBox2.setSelectedIndex(0);
        cbBox4.setSelectedIndex(0);
        
        cbBox1.setBackground(new java.awt.Color(28, 181, 224));
        cbBox1.setForeground(java.awt.Color.WHITE);
        cbBox2.setBackground(new java.awt.Color(28, 181, 224));
        cbBox2.setForeground(java.awt.Color.WHITE);
        cbBox3.setBackground(new java.awt.Color(28, 181, 224));
        cbBox3.setForeground(java.awt.Color.WHITE);
        cbBox4.setBackground(new java.awt.Color(28, 181, 224));
        cbBox4.setForeground(java.awt.Color.WHITE);    
        
        btn1 = new JButton();
        btn1.setText("Cập nhật thông tin cho biểu đồ");
        btn1.setBackground(new java.awt.Color(28, 181, 224));
        btn1.setForeground(java.awt.Color.WHITE); 
        
        tabbedPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                tabChanged(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 900, Short.MAX_VALUE)
                    )
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                            
                        .addComponent(cbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
                        .addGap(5)
                        .addComponent(cbBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
                        .addGap(200)
                    )
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                            
                        .addComponent(cbBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
                        .addGap(5)
                        .addComponent(cbBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
                        .addGap(200)
                    )
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGap(190)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
                        .addGap(480)
                    )
                )
            )        

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)                
                    .addComponent(cbBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)    
                )
                .addGap(5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addGap(30)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );     
        
    }// </editor-fold>       
    
    private void tabChanged(ChangeEvent changeEvent) {
        
        int index = tabbedPane.getSelectedIndex();
        if (index != 0){
            label2.setVisible(false);
            cbBox3.setVisible(false);
            cbBox4.setVisible(false);
            
            label1.setText("Chọn thời gian thống kê:");
        }
        else {
            label2.setVisible(true);
            cbBox3.setVisible(true);
            cbBox4.setVisible(true);
            
            label1.setText("Chọn thời gian bắt đầu:");
        }
    }

    public void setDataToColumnChart(JPanel jpnItem, String type) {
        
        //create dataset
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 1; i < 13; i++){
            dataset.addValue(1000000 * i, "Doanh thu", type + " " + i);
        }
        
        //add dataset to chart
        JFreeChart barChart = ChartFactory.createBarChart(
                "Biểu đồ thống kê doanh thu",
                type, "VNĐ",
                dataset, PlotOrientation.VERTICAL, false, true, false);       
        
        //set color for column chart
        BarRenderer r = (BarRenderer)barChart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, new java.awt.Color(28, 181, 224));

        //add chart to panel
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(jpnItem.getWidth(), 321));
        
        jpnItem.removeAll();
        jpnItem.setLayout(new CardLayout());               
        jpnItem.add(chartPanel);       
        jpnItem.validate();
        jpnItem.repaint();
    }
    
    public void setDataToPieChart(JPanel jpnItem) {
     
        //create dataset
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue( "IPhone 5s" , new Double( 20 ) );  
        dataset.setValue( "SamSung Grand" , new Double( 20 ) );   
        dataset.setValue( "MotoG" , new Double( 40 ) );    

        //add dataset to chart
        JFreeChart pieChart = ChartFactory.createPieChart(
                "Biểu đồ thống kê doanh thu",   // chart title 
                dataset,          // data    
                true,             // include legend   
                true, 
                false);             

        //add chart to panel
        ChartPanel chartPanel = new ChartPanel(pieChart);
        chartPanel.setPreferredSize(new Dimension(jpnItem.getWidth(), 321));
        
        jpnItem.removeAll();
        jpnItem.setLayout(new CardLayout());               
        jpnItem.add(chartPanel);       
        jpnItem.validate();
        jpnItem.repaint();
    }
    
    
    private JTabbedPane tabbedPane;
    private JPanel panel1;  
    private JPanel panel2;
    private JPanel panel3;
    private JLabel label1;
    private JLabel label2;
    private JComboBox cbBox1;
    private JComboBox cbBox2;
    private JComboBox cbBox3;
    private JComboBox cbBox4;
    private JButton btn1;
}
